### ISSUE TITLE
Debugging output with "base dir" and "share dir"

### ISSUE THREAD

**Issue by standage** [oschwengers/referenceseeker#12]
Just started noticing ReferenceSeeker printing what looks like debugging output. Appears to be coming from [this line](https://github.com/oschwengers/referenceseeker/commit/c2780b1083a55035432d77ab83548198dc3e682d#diff-17f4e52d81c8d9282cc3b401fe25a55eR98). I assume this was not intended to be included in the release. If so, it should be printed to stderr so it does not clutter the output.

**Comment by oschwengers** [comment]
Thanks a lot! Did not recognize theses artifacts. Should be solved. I'll trigger a new release to push this also through BioConda.
