### ISSUE TITLE
[BUG] IndexError: list index out of range

### ISSUE THREAD

**Issue by Jwebster89** [oschwengers/referenceseeker#13]
When running referenceseeker 1.6.3 (installed with conda) with a custom database I received an "IndexError: list index out of range". 

> Traceback (most recent call last):
>   File "/home/user/miniconda3/envs/ref_seeker/bin/referenceseeker", line 10, in <module>
>     sys.exit(main())
>   File "/home/user/miniconda3/envs/ref_seeker/lib/python3.9/site-packages/referenceseeker/referenceseeker.py", line 96, in main
>     ref_genomes = util.read_reference_genomes(config)
>   File "/home/user/miniconda3/envs/ref_seeker/lib/python3.9/site-packages/referenceseeker/util.py", line 24, in read_reference_genomes
>     'name': cols[3]

I imported my genomes into the database without using the optional --organism flag and received this error. After checking the custom db.tsv and the util.py, it looks like I might have needed something in the name column other than the default "". Re-ran the database import with the --organism flag and it appears to be working now.

**Comment by oschwengers** [comment]
Hello @Jwebster89 , thanks for reporting!
The issue should be fixed. ReferenceSeeker now sets a default `organism` strings to 'NA' if no organism name is provided.
A patch release is out - it should make its way through the CD (PyPI/Docker/BioConda) soon.

I close the issue for now - please do not hesitate to reopen it, if the issue should somehow remain.
Best regards!
