### ISSUE TITLE
<NA/> is being added to the start of file path

### ISSUE THREAD

**Issue by Rob-murphys** [oschwengers/referenceseeker#19]
**Describe the bug**
`NA/` is being added to the start of file path resulting it it not being added to database

*Input:*
`referenceseeker_db import --db /home/people/robmur/ku_00014/data/termitomyces/referenceSeeker_db/termitomyces --genome /home/people/robmur/ku_00014/data/termitomyces/sequences/D53_scaffolds.fasta`

*Output:*
`ERROR: could not import genome (NA//home/people/robmur/ku_00014/data/termitomyces/sequences/D53_scaffolds.fasta) into database (/home/people/robmur/ku_00014/data/termitomyces/referenceSeeker_db/termitomyces)!`

*Proof file exists:*
```
(base) [robmur@g-12-l0002 phylogeny]$ ll /home/people/robmur/ku_00014/data/termitomyces/sequences/D53_scaffolds.fasta
-rw-rw-r-- 1 robmur ku_00014 196777164 Apr 21 11:00 /home/people/robmur/ku_00014/data/termitomyces/sequences/D53_scaffolds.fasta
```

The organism name is being added to the front of the `--genome`  file path. It seems this is only added in the error report but not during the actual import so I am none the wiser as to what the actual issue is.

The sequence does seems to be getting added to the database under the name of the first record in the fasta file. Looks like it is in the mash or tsv creation steps then maybe?

**Comment by oschwengers** [comment]
Hi @Lamm-a , thanks for reporting this issue.
I've fixed a couple of minor issues and added some more CI tests to cover these better.
A new release `v1.7.3` is on its way: https://github.com/oschwengers/referenceseeker/releases/tag/v1.7.3
I'll let you know when it is available via Bioconda.

**Comment by oschwengers** [comment]
@Lamm-a the new version `v1.7.3` is now available via conda. Could you please try it again with the new version?

**Comment by Rob-murphys** [comment]
@oschwengers Awesome thank you ! I will give it a go then let you know, in a couple of hours unfortunatly as I am in the wet lab today.

**Comment by Rob-murphys** [comment]
@oschwengers issue fixed. The genomes now successfully imported. Both the `.msh` and `.tsv` are now populated.
