### ISSUE TITLE
[BUG] I can't make a custom db with referenceseeker_db init

### ISSUE THREAD

**Issue by drelo** [oschwengers/referenceseeker#25]
**Describe the bug**

I am trying to use this software that seems to do exactly what I want which is to compare my _500_ MAGs against a custom database of _18000_ genomes. I tried to build a database with a few of these genomes (only 10 of them). I tried different ways and renamed the fasta headers and/or filenames. To discard any problem with my data now I went back to the example data. 
Maybe I am confused in the way this works or for some reason I couldn't make `referenceseeker_db init` work. 

Thank you very much for your help

- what exactly happened
I picked the genomes inside the test/db folder, uncompressed them and put only these 3 in a new folder called 'DATA'

> ls DATA
> GCF_000439415.1.fna  GCF_002211925.1.fna  GCF_900205275.1.fna

Now I try to build the database and it leaves empty db.msh and db.tsv files. 
- what exact command was executed: just copy-paste the command line
`referenceseeker_db init --output ./DATA/ --db db`
- what installation of ReferenceSeeker did you use: `BioConda`, `GitHub`, `Pip`
BioConda
- what database was used: `public`, `custom`, which taxon
custom
- which version of ReferenceSeeker was used
referenceseeker 1.8.0

**Comment by oschwengers** [comment]
Hi @drelo , thanks for reaching out. I think the readme needs a little bit of improvement here. The creation of a custom DB is a two step process:
1. A new DB is created via `referenceseeker_db init`
2. New DB _entries_ are imported one by one via `referenceseeker_db import --db <DB> --genome <GENOME>`

So, your command is correct but only initializes a new DB. You need to import each genome into this new DB via the `import` command. A full usage is provided here: https://github.com/oschwengers/referenceseeker#custom-database
For 18,000 genomes, of course this needs to be automized, e.g. via a simple bash loop:
```
for f in `ls ./DATA`;
do
    referenceseeker_db import --db ./test-db --genome test/db/GCF_002211925.1.fna.gz;
done
```
Everything more advanced (taxonomy, custom ID, etc) would require some more elaborated scripting.

I've added a full round trip example to the readme: https://github.com/oschwengers/referenceseeker/commit/687ae6f200ba80fde7798b64f99f4be7c82208a2

Let me know if this helps or if there any further questions/issues.
Best regards!

**Comment by drelo** [comment]
Hi again, thank you very much for the help  @oschwengers, I thought the import was for incorporating some additional genomes in a later step and I missed the obvious alternative. This for loop worked with my custom data. Thanks again!
