### ISSUE TITLE
Database update

### ISSUE THREAD

**Issue by MostafaYA** [oschwengers/referenceseeker#28]
Hi, 

The pre-built `referenceseeker` databases have not been updated since a while, causing some new species not to be detected. Would you please consider an update? I assume one can do this with the `referenceseeker_db init` but if you detail this in the README for the RefSeq Bacteria for example, that would be great

Thank you!

**Comment by oschwengers** [comment]
Hi @MostafaYA,
thanks for reaching out. Indeed, they've become quite old. I'll put an update on my ToDo and try to address this ASAP.

**Comment by oschwengers** [comment]
@MostafaYA I just finished and published a new version of the RS database: https://doi.org/10.5281/zenodo.10488564

Due to the Zenodo standard storage quota, I couldn't upload the GTDB bacteria part, if this is of interest, I'll figure out how to provide it, as well.

**Comment by MostafaYA** [comment]
Thanks !!

**Comment by GuilhemRoyer** [comment]
Hi Oliver,

Thank you for this nice tool. Have you found a way to share the latest GTDB update? I'll be highlyinterested to get the last version.

Thanks,
