### ISSUE TITLE
Continuous integration

### ISSUE THREAD

**Issue by standage** [oschwengers/referenceseeker#5]
Following up on #4, if ReferenceSeeker had an automated test suite, it would also be possible to go a step further and set up a continuous integration environment using a service like GitHub Actions.

- While software is under active development, CI services can be configured to run a test suite and time updates are made to the code (such as from a push to `master` or a pull request from the community). The repo can also be configured so that any pull request submitted by the core developer(s) or the community cannot be merged until the tests pass.
- If/when software is in maintenance, CI services can be configured to run a test suite on a schedule, such as once per week or once per month. If future updates to package dependencies break ReferenceSeeker, CI would ensure a notification is issued to the authors early so that the problem can be addressed quickly. This would make it possible for the authors to provide long-term support for the software with minimal effort.

**Comment by oschwengers** [comment]
Hi @standage , thanks for your comment!

I added a new `tests` directory comprising 2 new test modules comprising 9 unit-tests testing:
- the calculation of `ANI` and `conDNA` values
- the creation of to-be-aligned nucleotide fragments
to start with.

Right now, I cannot come up with more unit tests which could be added without having to refactor major parts of the software. Any ideas/comments very much appreciated!

Additionally, I setup a Python package CI workflow via GitHub Actions which triggers:
- packaging
- testing
the software on all combinations of:
- OS: ubuntu-16.04, ubuntu-18.04, ubuntu-latest, macos-latest
- Python versions: 3.5, 3.6, 3.7, 3.8

Just in case I missed something, please, don't hesitate to ask. If not, I'd close this issue.

**Comment by oschwengers** [comment]
@standage Once again for pointing to GitHub actions! I just added an `PyPI` deploy action - might save some time on future releases.

**Comment by standage** [comment]
Looks great. Thanks!
