### ISSUE TITLE
Feature request: ability to include private data

### ISSUE THREAD

**Issue by standage** [oschwengers/referenceseeker#6]
Consider two hypothetical scenarios.

- a food-borne illness lab with numerous well-annotated *Salmonella* genomes beyond what's available in RefSeq
- an infectious disease lab with numerous well-annotated *Yersinia pestis* strains not publicly available

It would be helpful to scientists in labs like these to be able to include private data along with RefSeq genomes, either during the build process or by adding them later.

**Comment by oschwengers** [comment]
Hi @standage , @nick60 ,
I just implemented a new database `init` and `import` logic and added a new `referenceseeker_db` cli. A brief description was also added to the database readme section.  

I conducted some preliminary but successful tests so feel free to give it try.

As for now, it's only on GitHub but I'll put it on PyPI & BioConda as soon as I did some more tests.

**Comment by standage** [comment]
This is 🔥. Can't wait to try it!

**Comment by oschwengers** [comment]
@standage There was a tiny but nasty bug lurking in the database creation code. I did some further tests today and now, everything seems to work.

I'll close this issue and create a new release containing all recent changes. If you'll be facing any bugs or issues related to this, please feel free to reopen this issue or open a new one.
