### ISSUE TITLE
[BUG] Updating database script errors

### ISSUE THREAD

**Issue by samlhao** [oschwengers/referenceseeker#8]
Hello, while I was trying to build the database for bacteria, I noticed a couple of bugs in the scripts to automate building the database:

In [build-db.nf](https://github.com/oschwengers/referenceseeker/blob/4d2951d75b6a923fb11a0a294c1dfff59a1fb831/db-scripts/build-db.nf#L48), `$REFERENCE_SEEKER_HOME` needs to be escaped since it's a shell variable: `\$REFERENCE_SEEKER_HOME`. Also, the script assumes `share` is available in this directory, which is not detailed in the instructions.

In [build-db.sh](https://github.com/oschwengers/referenceseeker/blob/4d2951d75b6a923fb11a0a294c1dfff59a1fb831/db-scripts/build-db.sh#L30), `nextflow run` is missing. This also assumes that `$REFERENCE_SEEKER_HOME` contains the `build-db.nf` script, which isn't mentioned in instructions.

It worked after these tweaks, but it would be great if the documentation was more precise on how to use these!

**Comment by oschwengers** [comment]
Hi @samlhao , thanks for pointing out. Seems to be a proper bug. I guess you have installed it via `BioConda` ? I indeed forgot to add a notice that the `share` folder is not available via the `BioConda` installation. I'll add a proper description and notice to this - though it may take I while.
Thanks a lot!

**Comment by oschwengers** [comment]
Hi @samlhao ,
I just fixed the bugs you've mentioned above and added a hint that for this feature the repo clone should be used. I tested it (protozoa), worked as expected. 

Just reopen this and let me know if you still face any issues.
Again, thanks for pointing me to this!
